# Generated by Django 2.2.7 on 2019-11-23 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Время',
                'verbose_name_plural': 'Время',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_five', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_five', to='api.Days', verbose_name='Пятница')),
                ('day_four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_four', to='api.Days', verbose_name='Четверг')),
                ('day_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_one', to='api.Days', verbose_name='Понедельник')),
                ('day_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_three', to='api.Days', verbose_name='Среда')),
                ('day_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_two', to='api.Days', verbose_name='Вторник')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='api.Groups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='api.Rooms', verbose_name='Аудитория')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='api.Subjects', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='api.Teachers', verbose_name='Преподаватель')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='api.Times', verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Ячейка пары',
                'verbose_name_plural': 'Ячейки пар',
            },
        ),
        migrations.AddField(
            model_name='days',
            name='item_eight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_eight', to='api.Items', verbose_name='Восьмая пара'),
        ),
        migrations.AddField(
            model_name='days',
            name='item_five',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_five', to='api.Items', verbose_name='Пятая пара'),
        ),
        migrations.AddField(
            model_name='days',
            name='item_four',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_four', to='api.Items', verbose_name='Четвертая пара'),
        ),
        migrations.AddField(
            model_name='days',
            name='item_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_one', to='api.Items', verbose_name='Первая пара'),
        ),
        migrations.AddField(
            model_name='days',
            name='item_seven',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_seven', to='api.Items', verbose_name='Седьмая пара'),
        ),
        migrations.AddField(
            model_name='days',
            name='item_six',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_six', to='api.Items', verbose_name='Шестая пара'),
        ),
        migrations.AddField(
            model_name='days',
            name='item_three',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_three', to='api.Items', verbose_name='Третья пара'),
        ),
        migrations.AddField(
            model_name='days',
            name='item_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_two', to='api.Items', verbose_name='Вторая пара'),
        ),
    ]
